name: Tests

on:
  push:
    branches: [main, master]
    paths-ignore:
      - "pretix_mandatory_product/locale/**"
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "pretix_mandatory_product/locale/**"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install system dependencies
        run: sudo apt update && sudo apt install gettext
      - name: Install pretix
        run: pip3 install pretix
      - name: Install Dependencies
        run: pip3 install pytest pytest-django
      - name: Install Project
        run: python setup.py develop
      - name: Run checks
        run: py.test tests
